### ISSUE TITLE
instantiated Block style change

### ISSUE THREAD

**Issue by electroheadfx** [HansSchouten/PHPageBuilder#16] opened 2020-05-28 06:41 UTC
When I drag and drop a block called 'Content01', then I style its background color for exemple, if I drag and drop a new 'Content01' block, the instantiated new block inherit the background color of the first instantiated Content01 block. When I change the background color of any Content01 block, it changes all the two Content01 blocks. Is it possible to have customs change to each instantiated block ?

**Comment by HansSchouten** [comment] 2020-05-28 06:45
Hmm this sounds like a bug that I have to look into. Thanks for noticing.

**Comment by mobmoss** [comment] 2020-06-09 13:42
Hello, is this issue was solved in current build? Thanks

**Comment by HansSchouten** [comment] 2020-06-15 15:09
I just tried with various types of block, inside a container element and directly inside the page. I cannot reproduce the error. Can you share the view for which it does not work. Is it a .php file?

**Comment by electroheadfx** [comment] 2020-06-15 17:05
Both block have .fdb-block class.

![Capture d’écran 2020-06-15 à 19 03 15](https://user-images.githubusercontent.com/1211149/84685634-e4cfa980-af3a-11ea-9e5b-0ef615fb4da2.png)

![Capture d’écran 2020-06-15 à 19 05 15](https://user-images.githubusercontent.com/1211149/84685783-206a7380-af3b-11ea-8053-be87678fa4ec.png)

config.php:
<?php
return [
    'title' => 'Content',
    'category' => 'Contents',
    'icon' => 'fa fa-hand-peace-o',
    'thumb' => 'toto.jpg',
];

I will test it with your new release yet.

**Comment by HansSchouten** [comment] 2020-06-15 17:41
The background color should be assigned to a random id and not with the .fdb-block class. I will check whether I can reproduce the error if I give a class to a block.

**Closed** 2020-10-03 08:39 UTC
